AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  TransactionTable:
    Type: String
    Default: ChurchMemberProd

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Api:
        Cors:
          AllowMethods: "'OPTIONS,POST,GET,DELETE,PUT'"
          AllowHeaders: "'Origin, X-Requested-With, Content-Type, Accept, Authorization, Site, Platforms, Version'"
          AllowOrigin: "'*'"
        Auth:
          DefaultAuthorizer: MyCognitoAuthorizer
          Authorizers:
            MyCognitoAuthorizer:
              UserPoolArn:
                Fn::Sub: arn:aws:cognito-idp:ap-southeast-2:590184025842:userpool/ap-southeast-2_DC1bl9D2J


  ChurchMembersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/ScratchLambda/
      Handler: ScratchLambda::ScratchLambda.Function::FunctionHandler
      Runtime: dotnet8
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
      - AWSLambdaBasicExecutionRole
      - DynamoDBCrudPolicy:
            TableName: !Ref TransactionTable
      Events:
        GetMembers:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /members
            Method: get

# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Globals:
  Function:
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
